[package]
name = "substrate-runtime-template"
authors = ['Substrate DevHub <https://github.com/substrate-developer-hub>']
description = 'Substrate FRAME pallet template'
edition = '2018'
homepage = 'https://substrate.io'
license = 'Unlicense'
repository = 'https://github.com/paritytech/substrate/'
version = '2.0.0-alpha.8'

[dependencies]
# External Dependencies
parity-scale-codec = { version = "1.3.0", default-features = false, features = ["derive"] }
serde = { version = "1.0", optional = true, features = ["derive"] }

# Substrate Pallets
balances = { package = 'pallet-balances', version = '2.0.0-alpha.8', default-features = false }
randomness-collective-flip = { package = 'pallet-randomness-collective-flip', version = '2.0.0-alpha.8', default-features = false }
sudo = { package = 'pallet-sudo', version = '2.0.0-alpha.8', default-features = false }
transaction-payment = { package = 'pallet-transaction-payment', version = '2.0.0-alpha.8', default-features = false }
timestamp = { package = 'pallet-timestamp', version = '2.0.0-alpha.8', default-features = false }

# Other Substrate dependencies
frame-executive = { version = '2.0.0-alpha.8', default-features = false }
frame-support = { version = '2.0.0-alpha.8', default-features = false }
frame-system = { version = '2.0.0-alpha.8', default-features = false }
sp-api = { version = '2.0.0-alpha.8', default-features = false }
sp-block-builder = { version = '2.0.0-alpha.8', default-features = false }
sp-core = { version = '2.0.0-alpha.8', default-features = false }
sp-inherents = { version = '2.0.0-alpha.8', default-features = false }
sp-io = { version = '2.0.0-alpha.8', default-features = false }
sp-offchain = { version = '2.0.0-alpha.8', default-features = false }
sp-runtime = { version = '2.0.0-alpha.8', default-features = false }
sp-session = { version = '2.0.0-alpha.8', default-features = false }
sp-std = { version = '2.0.0-alpha.8', default-features = false }
sp-transaction-pool = { version = '2.0.0-alpha.8', default-features = false }
sp-version = { version = '2.0.0-alpha.8', default-features = false }

# The Substrate Pallet Template
pallet-template = { git = 'https://github.com/substrate-developer-hub/substrate-pallet-template', tag = 'v2.0.0-alpha.8' }

[build-dependencies]
wasm-builder-runner = { package = "substrate-wasm-builder-runner", version = "1.0.4" }

[features]
default = ["std"]
std = [
	# External dependencies
	"parity-scale-codec/std",
	"serde",

	# Substrate dependencies alphabetically
	"frame-executive/std",
	"frame-support/std",
	"frame-system/std",
	"sp-api/std",
	"sp-block-builder/std",
	"sp-core/std",
	"sp-inherents/std",
	"sp-io/std",
	"sp-offchain/std",
	"sp-runtime/std",
	"sp-session/std",
	"sp-std/std",
	"sp-transaction-pool/std",
	"sp-version/std",

	# Substrate Pallets
	"balances/std",
	"randomness-collective-flip/std",
	"sudo/std",
	"timestamp/std",
	"transaction-payment/std",

	# The Substrate Pallet Template
	"pallet-template/std",
]
